### ISSUE TITLE
GSWireUniversal-1.4.4-1.4.5-b108Forge java.lang.NoClassDefFoundError: cpw/mods/fml/client/registry/ISimpleBlockRenderingHandler

### ISSUE THREAD

**Issue by npdev453** [agaricusb/MCPC-1.4.5#6]
CPCM build 002

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12.12.12 19:55
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: cpw/mods/fml/client/registry/ISimpleBlockRenderingHandler
    at grygrflzr.mods.glowstonewire.BlockGlowstoneWire.d(BlockGlowstoneWire.java:87)
    at xv.e(World.java:359)
    at lq.d(Entity.java:668)
    at iv.a(NetServerHandler.java:394)
    at ec.a(SourceFile:136)
    at cg.b(NetworkManager.java:289)
    at iv.d(NetServerHandler.java:123)
    at iw.b(ServerConnection.java:53)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
    at ho.r(DedicatedServer.java:228)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
    at fy.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.client.registry.ISimpleBlockRenderingHandler
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:141)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 14 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:178)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:133)
    ... 16 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.5
    Operating System: Linux (amd64) version 2.6.32-279.el6.x86_64
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4853175984 bytes (4628 MB) / 6318718976 bytes (6026 MB) up to 9589161984 bytes (9144 MB)
    JVM Flags: 2 total; -Xms6288M -Xmx10288M
    AABB Pool Size: 3823 (214088 bytes; 0 MB) allocated, 3624 (202944 bytes; 0 MB) used
    Suspicious classes: TreeGenerator, $Proxy3, $Proxy4, ...[com.avaje.ebean.config.dbplatform.DatabasePlatform, SQLitePlatform], [com.google.common.base.Predicate, Function, Joiner, ...], [com.google.common.collect.Maps, BiMap, MapDifference, ...], [com.google.common.io.Files, InputSupplier, OutputSupplier], [cpw.mods.fml.common.Loader, LoaderException, ModContainer, ...], [cpw.mods.fml.common.asm.FMLSanityChecker, MLDetectorClassVisitor, SideOnly], [cpw.mods.fml.common.asm.transformers.AccessTransformer, Modifier, MarkerTransformer, ...], [cpw.mods.fml.common.discovery.ModDiscoverer, ASMDataTable, ModCandidate, ...], [cpw.mods.fml.common.discovery.asm.ASMModParser, ModClassVisitor, ModAnnotationVisitor, ...], [cpw.mods.fml.common.event.FMLEvent, FMLLoadEvent, FMLStateEvent, ...], [cpw.mods.fml.common.functions.ModIdFunction], [cpw.mods.fml.common.modloader.BaseModProxy], [cpw.mods.fml.common.network.Player, FMLNetworkHandler, NetworkModHandler, ...], [cpw.mods.fml.common.registry.BlockProxy, ItemProxy, LanguageRegistry, ...], [cpw.mods.fml.common.toposort.ModSortingException, ModSorter, DirectedGraph, ...], [cpw.mods.fml.common.versioning.ArtifactVersion, VersionParser, InvalidVersionSpecificationException, ...], [cpw.mods.fml.server.FMLServerHandler], [drzhark.customspawner.CustomSpawner], [drzhark.mocreatures.MoCreatures, MoCServerPacketHandler, MoCProxy, ...], [drzhark.mocreatures.client.MoCClientPacketHandler], [ee.lutsu.alpha.minecraft.TList, Leaf, Node], [extrabiomes.api.Api, BiomeManager], [grygrflzr.mods.glowstonewire.GlowstoneWireMod, ItemGlowstone, CommonProxy, ...], [mcpc.com.google.common.base.Preconditions, Charsets, Splitter, ...], [mcpc.com.google.common.cache.CacheLoader, CacheBuilder, Cache, ...], [mcpc.com.google.common.collect.Multimap, ListMultimap, AbstractMultimap, ...], [mcpc.com.google.common.eventbus.EventBus, HandlerFindingStrategy, AnnotatedHandlerFinder, ...], [mcpc.com.google.common.hash.Hashing, HashFunction, AbstractStreamingHashFunction, ...], [mcpc.com.google.common.io.LineProcessor, Resources, InputSupplier, ...], [mcpc.com.google.common.primitives.Ints, UnsignedBytes, Bytes], [mcpc.com.google.common.reflect.TypeCapture, TypeToken, SimpleTypeToken, ...], [mcpc.com.google.common.util.concurrent.UncheckedExecutionException, ExecutionError, MoreExecutors, ...], [net.minecraft.server.BaseMod, CrashReportCategory], [net.minecraftforge.common.IPlantable, IShearable, ISidedInventory, ...], [net.minecraftforge.event.Event, ListenerList, CommandEvent, ...], [net.minecraftforge.event.entity.EntityEvent, EntityJoinWorldEvent, PlaySoundAtEntityEvent, ...], [net.minecraftforge.event.entity.item.ItemEvent, ItemExpireEvent, ItemTossEvent], [net.minecraftforge.event.entity.living.LivingEvent, LivingSetAttackTargetEvent, LivingUpdateEvent, ...], [net.minecraftforge.event.entity.player.PlayerEvent, ArrowNockEvent, ArrowLooseEvent, ...], [net.minecraftforge.event.world.WorldEvent, Load, Unload, ...], [net.minecraftforge.oredict.OreDictionary, OreRegisterEvent, ShapedOreRecipe, ...], [net.minecraftforge.transformers.ForgeAccessTransformer, EventTransformer], [org.apache.commons.lang.Validate, UnhandledException, StringUtils, ...], [org.apache.commons.lang.exception.Nestable, NestableRuntimeException], [org.bukkit.BlockChangeDelegate, World, Server, ...], [org.bukkit.block.BlockFace, BlockState, Block, ...], [org.bukkit.command.CommandSender, RemoteConsoleCommandSender, CommandException, ...], [org.bukkit.command.defaults.VanillaCommand, SaveCommand, SaveOnCommand, ...], [org.bukkit.configuration.ConfigurationSection, Configuration, MemorySection, ...], [org.bukkit.configuration.file.FileConfiguration, YamlConfiguration, FileConfigurationOptions, ...], [org.bukkit.configuration.serialization.ConfigurationSerializable, ConfigurationSerialization, DelegateDeserialization, ...], [org.bukkit.conversations.Conversable, ConversationCanceller], [org.bukkit.craftbukkit.Main, LoggerOutputStream, CraftServer, ...], [org.bukkit.craftbukkit.block.CraftBlock, CraftBlockState], [org.bukkit.craftbukkit.command.ServerCommandSender, CraftConsoleCommandSender, ColouredConsoleSender], [org.bukkit.craftbukkit.conversations.ConversationTracker], [org.bukkit.craftbukkit.enchantments.CraftEnchantment], [org.bukkit.craftbukkit.entity.CraftEntity, CraftLivingEntity, CraftHumanEntity, ...], [org.bukkit.craftbukkit.event.CraftEventFactory], [org.bukkit.craftbukkit.generator.InternalChunkGenerator, CustomChunkGenerator, NormalChunkGenerator, ...], [org.bukkit.craftbukkit.help.SimpleHelpMap, CommandAliasHelpTopic, HelpYamlReader, ...], [org.bukkit.craftbukkit.inventory.CraftItemStack, CraftRecipe, CraftShapedRecipe, ...], [org.bukkit.craftbukkit.libs.com.google.gson.JsonDeserializer, JsonParseException, GsonBuilder, ...], [org.bukkit.craftbukkit.libs.com.google.gson.annotations.SerializedName], [org.bukkit.craftbukkit.libs.com.google.gson.internal.Excluder, $Gson$Preconditions, Primitives, ...], [org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.JsonTreeReader, JsonTreeWriter, BigDecimalTypeAdapter, ...], [org.bukkit.craftbukkit.libs.com.google.gson.reflect.TypeToken], [org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader, JsonWriter, MalformedJsonException, ...], [org.bukkit.craftbukkit.libs.jline.Terminal, TerminalSupport, UnsupportedTerminal, ...], [org.bukkit.craftbukkit.libs.jline.console.ConsoleReader, CursorBuffer, ConsoleKeys, ...], [org.bukkit.craftbukkit.libs.jline.console.completer.CompletionHandler, CandidateListCompletionHandler], [org.bukkit.craftbukkit.libs.jline.console.history.History, MemoryHistory], [org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader, Configuration, Log], [org.bukkit.craftbukkit.libs.joptsimple.OptionException, OptionParser, OptionSpec, ...], [org.bukkit.craftbukkit.libs.joptsimple.internal.AbbreviationMap, ReflectionException, Reflection, ...], [org.bukkit.craftbukkit.libs.joptsimple.util.KeyValuePair], [org.bukkit.craftbukkit.metadata.EntityMetadataStore, PlayerMetadataStore, WorldMetadataStore, ...], [org.bukkit.craftbukkit.potion.CraftPotionEffectType, CraftPotionBrewer], [org.bukkit.craftbukkit.scheduler.CraftScheduler, CraftAsyncDebugger, CraftTask, ...], [org.bukkit.craftbukkit.updater.AutoUpdater, BukkitDLUpdaterService, DateDeserializer, ...], [org.bukkit.craftbukkit.util.ServerShutdownThread, Waitable, TerminalConsoleHandler, ...], [org.bukkit.enchantments.Enchantment, EnchantmentWrapper], [org.bukkit.entity.EntityType, Entity, LivingEntity, ...], [org.bukkit.event.Event, Cancellable, Listener, ...], [org.bukkit.event.block.BlockEvent, BlockFadeEvent, BlockGrowEvent, ...], [org.bukkit.event.entity.EntityEvent, EntityInteractEvent, EntityDamageEvent, ...], [org.bukkit.event.hanging.HangingEvent, HangingPlaceEvent, HangingBreakEvent, ...], [org.bukkit.event.inventory.InventoryEvent, InventoryOpenEvent, PrepareItemCraftEvent, ...], [org.bukkit.event.painting.PaintingEvent, PaintingPlaceEvent, PaintingBreakEvent, ...], [org.bukkit.event.player.PlayerEvent, PlayerInteractEvent, PlayerFishEvent, ...], [org.bukkit.event.server.Packet, ServerEvent, MapInitializeEvent, ...], [org.bukkit.event.vehicle.VehicleEvent, VehicleCollisionEvent, VehicleBlockCollisionEvent, ...], [org.bukkit.event.weather.WeatherEvent, ThunderChangeEvent, WeatherChangeEvent, ...], [org.bukkit.event.world.WorldEvent, WorldInitEvent, WorldSaveEvent, ...], [org.bukkit.generator.ChunkGenerator], [org.bukkit.help.HelpMap, HelpTopic, IndexHelpTopic, ...], [org.bukkit.inventory.ItemStack, Recipe, ShapedRecipe, ...], [org.bukkit.map.MapView], [org.bukkit.material.MaterialData, Tree, Directional, ...], [org.bukkit.metadata.Metadatable, MetadataStoreBase, MetadataStore], [org.bukkit.permissions.ServerOperator, Permissible, PermissionDefault, ...], [org.bukkit.plugin.ServicesManager, PluginManager, SimpleServicesManager, ...], [org.bukkit.plugin.java.JavaPluginLoader, PluginClassLoader, JavaPlugin], [org.bukkit.plugin.messaging.PluginMessageRecipient, Messenger, StandardMessenger, ...], [org.bukkit.potion.PotionEffectType, PotionEffectTypeWrapper, PotionBrewer, ...], [org.bukkit.scheduler.BukkitScheduler, BukkitTask, BukkitWorker], [org.bukkit.util.Vector, BlockVector, NumberConversions], [org.bukkit.util.permissions.DefaultPermissions, CommandPermissions, BroadcastPermissions], [org.fusesource.jansi.Ansi, NoAnsi, Color, ...], [org.json.simple.JSONAware, JSONStreamAware, JSONArray, ...], [org.json.simple.parser.JSONParser, ParseException, Yylex, ...], [org.objectweb.asm.ClassVisitor, ClassWriter, MethodVisitor, ...], [org.objectweb.asm.tree.ClassNode, MethodNode, FieldNode, ...], [org.sqlite.JDBC, Conn, SQLiteConfig, ...], [org.yaml.snakeyaml.DumperOptions, ScalarStyle, FlowStyle, ...], [org.yaml.snakeyaml.composer.Composer, ComposerException], [org.yaml.snakeyaml.constructor.BaseConstructor, SafeConstructor, Constructor, ...], [org.yaml.snakeyaml.emitter.Emitable, Emitter, EmitterState, ...], [org.yaml.snakeyaml.error.YAMLException, MarkedYAMLException, Mark], [org.yaml.snakeyaml.events.Event, NodeEvent, ScalarEvent, ...], [org.yaml.snakeyaml.external.com.google.gdata.util.common.base.Escaper, UnicodeEscaper, PercentEscaper], [org.yaml.snakeyaml.introspector.PropertyUtils, BeanAccess], [org.yaml.snakeyaml.nodes.Node, CollectionNode, MappingNode, ...], [org.yaml.snakeyaml.parser.Parser, ParserImpl, Production, ...], [org.yaml.snakeyaml.reader.UnicodeReader, StreamReader, ReaderException], [org.yaml.snakeyaml.representer.BaseRepresenter, SafeRepresenter, Representer, ...], [org.yaml.snakeyaml.resolver.Resolver, ResolverTuple], [org.yaml.snakeyaml.scanner.Scanner, ScannerImpl, ScannerException, ...], [org.yaml.snakeyaml.serializer.Serializer, SerializerException], [org.yaml.snakeyaml.tokens.Token, AliasToken, ScalarToken, ...], [org.yaml.snakeyaml.util.UriEncoder, ArrayStack]
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    CraftBukkit Information: 
   Running: CraftBukkit-CPCM version null (MC: 1.4.5) (Implementing API version Unknown-Version) false
   Plugins: { PreciousStones v9.5.2 net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones [Phaed],}
   Warnings: DEFAULT
   Threads: { TIMED_WAITING pool-1-thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Connection #21 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], RUNNABLE Connection #16 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], RUNNABLE Connection #10 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Connection #10 write thread: [java.lang.Thread.sleep(Native Method), ci.run(NetworkWriterThread.java:38)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)], RUNNABLE DestroyJavaVM: [], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1618), org.bukkit.craftbukkit.CraftCrashReport.call(CraftCrashReport.java:28), l.a(SourceFile:74), a.h(CrashReport.java:47), a.<init>(CrashReport.java:34), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:475), fy.run(SourceFile:856)], RUNNABLE Thread-6: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:242), java.io.BufferedInputStream.fill(BufferedInputStream.java:235), java.io.BufferedInputStream.read(BufferedInputStream.java:254), java.io.FilterInputStream.read(FilterInputStream.java:83), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), hq.run(ThreadCommandReader.java:33)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), aip.b(SourceFile:43), aip.run(SourceFile:22), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING Thread-57: [java.lang.Thread.sleep(Native Method), cj.run(SourceFile:297)], RUNNABLE Connection #5 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], RUNNABLE Connection #29 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], RUNNABLE Connection #32 write thread: [java.net.SocketOutputStream.socketWrite0(Native Method), java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109), java.net.SocketOutputStream.write(SocketOutputStream.java:153), net.minecraft.org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source), java.io.BufferedOutputStream.write(BufferedOutputStream.java:122), java.io.DataOutputStream.write(DataOutputStream.java:107), du.a(Packet56MapChunkBulk.java:155), eg.a(Packet.java:155), cg.h(NetworkManager.java:99), cg.d(NetworkManager.java:348), ci.run(NetworkWriterThread.java:21)], TIMED_WAITING Connection #21 write thread: [java.lang.Thread.sleep(Native Method), ci.run(NetworkWriterThread.java:38)], TIMED_WAITING Thread-5: [java.lang.Thread.sleep(Native Method), hp.run(SourceFile:52)], RUNNABLE Listen thread: [java.net.PlainSocketImpl.socketAccept(Native Method), java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398), java.net.ServerSocket.implAccept(ServerSocket.java:522), java.net.ServerSocket.accept(ServerSocket.java:490), hu.run(DedicatedServerConnectionThread.java:64)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:177)], WAITING Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), cpw.mods.fml.relauncher.FMLRelaunchLog$ConsoleLogThread.run(FMLRelaunchLog.java:64), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING pool-1-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Connection #32 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], TIMED_WAITING Thread-59: [java.lang.Thread.sleep(Native Method), cj.run(SourceFile:297)], RUNNABLE Connection #15 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.a(Unknown Source), net.minecraft.org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), eg.a(Packet.java:105), cg.i(NetworkManager.java:189), cg.c(NetworkManager.java:344), ch.run(SourceFile:93)], TIMED_WAITING Connection #29 write thread: [java.lang.Thread.sleep(Native Method), ci.run(NetworkWriterThread.java:38)], TIMED_WAITING Connection #5 write thread: [java.lang.Thread.sleep(Native Method), ci.run(NetworkWriterThread.java:38)], TIMED_WAITING Connection #16 write thread: [java.lang.Thread.sleep(Native Method), ci.run(NetworkWriterThread.java:38)], TIMED_WAITING Connection #15 write thread: [java.lang.Thread.sleep(Native Method), ci.run(NetworkWriterThread.java:38)],}
   Recent tasks from 491-521{PreciousStones:net.sacredlabyrinth.Phaed.PreciousStones.managers.StorageManager$1@331,}
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NoSuchFieldError: c
    Player Count: 7 / 88; [iq['Artem6085'/117, l='world', x=47,59, y=65,00, z=55,21](Artem6085 at 47.58765349271147,65.0,55.21044505401501), iq['STRELOK'/175, l='world', x=47,82, y=65,00, z=56,66](STRELOK at 47.81800658909926,65.0,56.661086552213725), iq['admin'/281, l='world', x=46,60, y=65,00, z=54,01](admin at 46.60102777124555,65.0,54.01223102133275), iq['facepalm'/283, l='world', x=47,10, y=65,00, z=56,26](facepalm at 47.09719172985481,65.0,56.26420286416467), iq['007'/365, l='world', x=65,02, y=62,21, z=44,28](007 at 65.01630983513306,62.20701847451004,44.28448296583572), iq['Hanomag_rus'/540, l='world', x=48,90, y=66,25, z=53,31](Hanomag_rus at 48.90231441985984,66.24918707874468,53.31173897319635), iq['Garrus'/616, l='world', x=311,95, y=64,00, z=146,90](Garrus at 311.9473499217459,64.0,146.90371459165215)]
    Is Modded: Definitely; Server brand changed to 'craftbukkit-cpcm'
    Type: Dedicated Server (map_server.txt)

**Comment by agaricusb** [comment]
Missing client class cpw/mods/fml/client/registry/ISimpleBlockRenderingHandler on the server

**Comment by agaricusb** [comment]
Glowstone Wire: http://www.minecraftforum.net/topic/944547-145-132-glowstone-wire-build108-ssp-smp-aesthetic/

**Comment by agaricusb** [comment]
The mod's Block class is accessing the client proxy on the server-side:

   public int d() {
      return ClientProxy.glowstoneWireRenderID;^M
   }

notice no @SideOnly(Side.CLIENT). 

On the other hand, this works in vanilla..

**Comment by agaricusb** [comment]
Works with CPCM 003.
